### ISSUE TITLE
Registration form is not visible for players

### ISSUE THREAD

**Issue by KestisMo** [pozil/quiz-host-app#50]
Registration form is not visible for players. Tried to reset the game, but it not fixed the problem.

**Comment by pozil** [comment]
Hi @KestisMo have you checked your the full and minifed url of the Heroku player app?

**Comment by KestisMo** [comment]
Hi @pozil Issue resolved, it was a bad credentials, because I made a mistake in salesforce org settings (scratch org). I tried again to create quiz from step 1 and it was working fine. Thank you.

**Comment by pozil** [comment]
Cool glad to hear that. Enjoy the app!
