### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by nishantspanwar** [pozil/quiz-host-app#52]
![Snap 2020-02-05 at 12 52 54](https://user-images.githubusercontent.com/8143071/73843395-7a815c80-4816-11ea-9b34-865570fc14f7.png)

**Comment by pozil** [comment]
Hi @nishantspanwar thanks for opening an issue but I can't do anything without the logs and a description of what you tried to do.

**Comment by nishantspanwar** [comment]
I just completed the setup as per the guide and then open the app. How can I get the logs when I look for logs (More > View logs) it shows nothing

**Comment by nishantspanwar** [comment]
I have the Build Logs if you can catch something from that.
`-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  >=10.0.0
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version >=10.0.0...
       Downloading and installing node 13.7.0...
       Using default npm version: 6.13.6
       
-----> Installing dependencies
       Installing node modules (package.json + package-lock)
       
       > quiz-player-app@1.0.0 preinstall /tmp/build_072e4ff920c2ac636a37ad9d24e98eee
       > rm -fr src/client/resources/dist
       
       
       > fibers_node_v8@3.1.5 preinstall /tmp/build_072e4ff920c2ac636a37ad9d24e98eee/node_modules/fibers_node_v8
       > node preinstall.js
       
       
       > fibers@4.0.2 install /tmp/build_072e4ff920c2ac636a37ad9d24e98eee/node_modules/fibers
       > node build.js || nodejs build.js
       
       make: Entering directory '/tmp/build_072e4ff920c2ac636a37ad9d24e98eee/node_modules/fibers/build'
         CXX(target) Release/obj.target/fibers/src/fibers.o
         CXX(target) Release/obj.target/fibers/src/coroutine.o
         CC(target) Release/obj.target/fibers/src/libcoro/coro.o
         SOLINK_MODULE(target) Release/obj.target/fibers.node
         COPY Release/fibers.node
       make: Leaving directory '/tmp/build_072e4ff920c2ac636a37ad9d24e98eee/node_modules/fibers/build'
       Installed in `/tmp/build_072e4ff920c2ac636a37ad9d24e98eee/node_modules/fibers/bin/linux-x64-79-glibc/fibers.node`
       
       > fibers_node_v8@3.1.5 install /tmp/build_072e4ff920c2ac636a37ad9d24e98eee/node_modules/fibers_node_v8
       > node build.js
       
       ignore install
       
       > husky@3.1.0 install /tmp/build_072e4ff920c2ac636a37ad9d24e98eee/node_modules/husky
       > node husky install
       
       husky > Setting up git hooks
       Command failed: git rev-parse --show-toplevel --git-common-dir
       fatal: not a git repository (or any parent up to mount point /)
       Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
       husky > Failed to install
       
       > ejs@3.0.1 postinstall /tmp/build_072e4ff920c2ac636a37ad9d24e98eee/node_modules/ejs
       > node ./postinstall.js
       
       
       > nodemon@2.0.2 postinstall /tmp/build_072e4ff920c2ac636a37ad9d24e98eee/node_modules/nodemon
       > node bin/postinstall || exit 0
       
       Love nodemon? You can now support the project via the open collective:
        > https://opencollective.com/nodemon/donate
       
       
       > husky@3.1.0 postinstall /tmp/build_072e4ff920c2ac636a37ad9d24e98eee/node_modules/husky
       > opencollective-postinstall || exit 0
       
       
       > quiz-player-app@1.0.0 postinstall /tmp/build_072e4ff920c2ac636a37ad9d24e98eee
       > mkdir -p src/client/resources/dist && cp node_modules/normalize.css/normalize.css src/client/resources/dist/.
       
       added 2129 packages from 958 contributors and audited 909355 packages in 72.04s
       
       29 packages are looking for funding
         run `npm fund` for details
       
       found 3 vulnerabilities (1 low, 1 moderate, 1 high)
         run `npm audit fix` to fix them, or `npm audit` for details
       
-----> Build
       Running build
       
       > quiz-player-app@1.0.0 build /tmp/build_072e4ff920c2ac636a37ad9d24e98eee
       > lwc-services build -m production
       
       
       ⚡⚡⚡⚡⚡  Lightning Web Components ⚡⚡⚡⚡⚡
       
       
       ⌛  Creating build configuration
       📦  Starting build process.
              Build duration: 8.013
       🎉  Build successfully created.
       
-----> Caching build
       - node_modules
       
-----> Pruning devDependencies
       
       > husky@3.1.0 preuninstall node_modules/husky
       > node husky uninstall
       
       husky > Uninstalling git hooks
       Command failed: git rev-parse --show-toplevel --git-common-dir
       fatal: not a git repository (or any parent up to mount point /)
       Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
       husky > Failed to uninstall
       removed 67 packages and audited 909048 packages in 18.051s
       
       28 packages are looking for funding
         run `npm fund` for details
       
       found 3 vulnerabilities (1 low, 1 moderate, 1 high)
         run `npm audit fix` to fix them, or `npm audit` for details
       
-----> Build succeeded!
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 90.4M
-----> Launching...
       Released v4
       https://lk-sf-devs.herokuapp.com/ deployed to Heroku`

**Comment by nishantspanwar** [comment]
I can add you as a collaborator if you want.

**Comment by pozil** [comment]
I don't think that's necessary. Looking at the logs, it seems that the app isn't connecting to Salesforce.
Can you double check your Heroku config variables (username, password, personal security token...) and restart the dyno?

**Comment by nishantspanwar** [comment]
Great! It worked. I used the access token generated by the SFDX CLI earlier using the 
`H:\QuizApp\quiz-host-app>sfdx force:user:display -u <username>` command.

I generated the security token and password with the legacy way from setup and it worked.

Thanks for the support and we can close the issue now.
