### ISSUE TITLE
RE-use of the same question in a quiz session results in a loop

### ISSUE THREAD

**Issue by codefriar** [pozil/quiz-host-app#55]
### Summary

Given: a quiz session of ten questions. 
When: two of the quiz session question records reference the same Question object and are back-to-back ie: indexes 6, 7
Then: The app enters into an infinite loop, presenting the same question over and over again. (Long past the 10 questions included in the quiz session

### App Version

Host app version (see bottom of host game page):
1.0.2

Player app version (see bottom of player registration page):
1.1.0
### Steps To Reproduce:

1.  Create a new Quiz Session
1. In the quiz session, create two quiz session questions
1. ensure that these two new quiz session questions are back-to-back, and reference the same question__c object
1. Create a third quiz session question record, referencing a different question

### Expected result

I expect it to progress to the third question.

### Actual result

It keeps looping to the same (first or second) question

**Comment by pozil** [comment]
Addressed by #57
