### ISSUE TITLE
Data Import Error during installation

### ISSUE THREAD

**Issue by orlybg** [pozil/quiz-host-app#58]
### Summary
Permission Issue on data import during Install

_Short summary of what is going on or to provide context_.
Running the installation script default arguments in Mac OS X

Everything goes well until data import when this error appears

Importing data...
ERROR running force:data:tree:import:  We couldn't process your request because you don't have access to Current_Question__c on Quiz_Session__c. To learn more about field-level security, visit Tips and Hints for Page Layouts and Field-Level Security in our Developer Documentation.
### App Version

Host app version (see bottom of host game page):
x.y.z

Player app version (see bottom of player registration page):
x.y.z

### Steps To Reproduce:

1. ./install-dev.sh quiz sample
2. Error appears

### Expected result
Succesful installation

_Describe what should have happened_.

### Actual result

ERROR running force:data:tree:import:  We couldn't process your request because you don't have access to Current_Question__c on Quiz_Session__c. To learn more about field-level security, visit Tips and Hints for Page Layouts and Field-Level Security in our Developer Documentation.

**Comment by pozil** [comment]
Thanks for reporting this @orlybg. For some reason, the field got removed from the permission set.
I released a new version with a fix.
