### ISSUE TITLE
Package app as a Managed Package

### ISSUE THREAD

**Issue by pozil** [pozil/quiz-host-app#63]
Package the app as a Managed Package in order to have it on the AppExchange for easy install/upgrades.

**Comment by chazzvader** [comment]
I would gladly be a tester for you if you did this.   Let me know how I can help make this happen.

**Comment by pozil** [comment]
@chazzvader can I take on your offer?
Can you try to install the app using the updated install instructions and let me know if I need to fix anything.

**Comment by pozil** [comment]
It's not on the AppExchange yet but you can install it with clicks as a managed package.

**Comment by chazzvader** [comment]
I will!   
I will let you know how it works for me.  

Thanks.

**Comment by pozil** [comment]
Did you get a chance to try it out @chazzvader?

**Comment by mbevinsuk** [comment]
@pozil I've just given this a go in my dev org and having a few issues. The Host app in the org is stuck on 'Loading....' message and doesn't give any messages on what's wrong.

When I installed the host app I had to assigned the permission set before I could see the object to enable the Change Data Capture settings. So it might be worth moving step 2 and 3 around.

Any suggestions on how to debug?

**Comment by pozil** [comment]
Thanks for trying it out @mbevinsuk. I rewrote the readme to be more readable and I found a bug with the player app (I need to include the package namespace in there).
I'll let you know when it's fixed.

**Comment by pozil** [comment]
Hey @mbevinsuk and @chazzvader I'm looking for testers for the package install. Can you give it a try and let me know if it works for you and if instructions are clear.

This was way more work than what I expected: I had to modify both apps (host and player) and the readme but I believe that I've nailed it.

**Comment by chazzvader** [comment]
Hi @pozil.   I just installed the package in a test org.  It works!

What may be helpful is could you supply a sample Session and a few sample questions with the app?  the package I installed had no data (questions) so for a brand new user this may be confusing to understand what to do next. 

I know you have documented how to load questions, but if you had some samples there for a reference, that may be helpful.   

thanks.

**Comment by mbevinsuk** [comment]
> Hey @mbevinsuk and @chazzvader I'm looking for testers for the package install. Can you give it a try and let me know if it works for you and if instructions are clear.
> 
> This was way more work than what I expected: I had to modify both apps (host and player) and the readme but I believe that I've nailed it.

Also works for me now, so great job at fixing it @pozil !

I completed an uninstall and reinstall of the managed package in my dev org and then deployed the Heroku app again after deleting the old version. 

I also had issue with the questions. I created session before like the instructions said at Step 3.7 when there weren't any questions. I then went to the Quiz Question tab and added 4 test quetions manually but when I went back to Session tab and selected the session I couldn't see them to be able to select from and add them to the session. I had to create another new session and then I could see them. Might be worth asking a few others to test this as it could have been something I did I guess.

**Comment by pozil** [comment]
Thank you both for testing and providing great feedback.

I just released a new version of the package with the following improvements:
- Added a package post-install script that creates a session with a sample question
- Added notice about unsaved changes in question picker on session record

This should address the last concerns so I'll close the issue. Do let me know if we need to re-open it.
