### ISSUE TITLE
Question:  What number of users should I upgrade my Dyno?

### ISSUE THREAD

**Issue by chazzvader** [pozil/quiz-host-app#64]
I am planning to use the app for a user group meeting soon that I have 60+ registrations. 

Is this too many users to host on the Free Dyno?  
When should I upgrade to the Hobby Dyno?  
100+ Users?  

just looking for a suggestion.   Thanks

**Comment by pozil** [comment]
If you have 60 registrations, you'll likely have less attendees/players and you should be fine with a free dyno.

I can't tell for sure where's the limit between the free dyno and the hobby dyno but I can tell you that another group played with 40-50 players on a free dyno and that worked well.
